#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/<%- clusterId %>
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001

  fleet:
    public-ip: $private_ipv4

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

  ssh_authorized_keys:
    - ssh-rsa: <%- sshKey %>
