#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/${TOKEN}
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001

  fleet:
    public-ip: $private_ipv4

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: virtual-vulcano.service
      command: start
      content: |
        [Unit]
        Description=Provision instance of Virtual Vulcano.

        Requires=etcd.service
        Requires=docker.service

        After=etcd.service
        After=docker.service

        [Service]
        User=core
        TimeoutStartSec=0
        KillMode=none
        EnvironmentFile=/etc/environment

        ExecStartPre=-/usr/bin/docker kill virtual-vulcano
        ExecStartPre=-/usr/bin/docker rm virtual-vulcano
        ExecStartPre=/usr/bin/docker pull virtualvulcano/web
        ExecStart=/usr/bin/docker run --name virtual-vulcano -p 80:8080 virtualvulcano/web

        ExecStop=/usr/bin/docker stop virtual-vulcano

        [Install]
        WantedBy=local.target
