
application: virtual-vulcano
version: alpha
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "365d"




skip_files:
- old
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*/build/.*
- ^(.*/)?.*/node_modules/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.md$
- ^(.*/)?datastore
- ^(.*/)?Thumbs\.db$
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*/out/.*
- ^(.*/)?.*/examples/.*
- ^(.*/)?.*/tools/.*
- ^(.*/)?.*/old/.*
- ^(.*/)?.*/build/.*

