# Copyright (c) 2014 The Virtual Vulcano authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that
# can be found in the LICENSE.md file.

application: virtual-vulcano
version: alpha
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "365d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "365d"

- url: /
  static_files: partials/index.html
  upload: partials/index.html

- url: /api/.*
  script: server.application

- url: /cloud-config/.*
  script: server.application


skip_files:
- old
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*/build/.*
- ^(.*/)?.*/node_modules/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.md$
- ^(.*/)?datastore
- ^(.*/)?Thumbs\.db$
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*/out/.*
- ^(.*/)?.*/examples/.*
- ^(.*/)?.*/tools/.*
- ^(.*/)?.*/old/.*
- ^(.*/)?.*/build/.*

