# Copyright (c) 2015 The Virtual Vulcano authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that
# can be found in the LICENSE.md file.

FROM mysql:5.6
MAINTAINER Virtual Vulcano <virtualvulcano@gmail.com>

ENV MYSQL_ROOT_PASSWORD virtualvulcano

CMD mysqld
