#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/6464555fa7d8e20c748142c1db8d7481
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001

  fleet:
    public-ip: $private_ipv4

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: cmd.service
      command: start
      content: |
        [Unit]
        Description=command

        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=/usr/bin/pwd

        [Install]
        WantedBy=local.target

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsnZXiFvGRud3yQB6fsGxCANza6a71Kmyk9mApU03LyCFwAj0ZQCYTAqcnQomAnMaVjVZoS1yD0WJu0gj2bIjuHKK8qc9l43o3tKp3ov+1pYdaXkP88eF9IA834LADGMmMVcRcKws57zcJLsld+jrnLvKB5GHWDxOAJMw7H/OSGjiCwFwvLAovEmCmMjHR+GyKxlMi/qn4bC2VtJOAXNrepPfKs9razdEVM9XDAwzPFQ/9NbDu5tSWVi/QFRZ8W+T13q6Ji+V3X//+6pK2ri3CjPS5m5yrAmzTU1K40CX8LIUcoj3bHMWNAblWGHZz0CP/TvT+roO9fveashBRQHQP root@db6a0c2475a2
